// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Haha.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class HahaHandler : virtual public HahaIf {
 public:
  HahaHandler() {
    // Your initialization goes here
  }

  void haha(std::string& _return, const std::string& s) {
    // Your implementation goes here
    printf("haha\n");
  }

  int32_t baga(const int32_t one, const int32_t two) {
    // Your implementation goes here
    printf("baga\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<HahaHandler> handler(new HahaHandler());
  ::std::shared_ptr<TProcessor> processor(new HahaProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

