/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef main_CONSTANTS_H
#define main_CONSTANTS_H

#include "main_types.h"



class mainConstants {
 public:
  mainConstants();

};

extern const mainConstants g_main_constants;



#endif
